{
 "title": "Nginx Lua",
 "description": "Nginx dashboard for nginx-lua-prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "instance",
    "query": "label_values(nginx_http_connections, instance)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_bucket{instance=\"$server\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx HTTP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_http_connections", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Requests Per Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{instance=\"$server\", host!~\"|127.0.0.1\"}[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request Duration Percentile - $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.999, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Request Duration Histogram - $host",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "idelta(nginx_http_request_duration_seconds_bucket{instance=\"$server\",host=\"$host\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests by Status - $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"$server\", host=\"$host\"}[2m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}